apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: docker-k8s-jenkins
        image: assistant16/docker-k8s-jenkins:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: httpport-test
          containerPort: 8080 
