apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  namespace : jenkins
spec:
  selector: 
    app: test-app
  type: NodePort  
  ports:
    - name: httpport-test
      port: 30003 
      targetPort: 30003 
      nodePort: 30003 
